# Generated by Django 5.0.3 on 2024-04-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_likes_count_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
